services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi_ecommerce
    restart: always
    env_file: .env
    volumes:
      - ./:/var/www
      - /var/www/vendor
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - app
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
    depends_on:
      - database
    networks:
      - app

  database:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: multi_ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./Sql File/eCommerce.sql:/docker-entrypoint-initdb.d/eCommerce.sql
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db:
